// Hand-authored demo feedback with pre-computed analysis.
// Story arcs for the demo:
//  - Engineering burnout / on-call load rising sharply over the last 4 weeks
//  - Sales confused and frustrated by the new commission plan (weeks 2–7)
//  - Customer Support praising the new helpdesk tooling rolled out ~6 weeks ago
//  - Organisation-wide debate about the new 3-days-in-office hybrid policy (weeks 3–8)
//  - A handful of critical items: harassment, safety, discrimination

type Sentiment = "positive" | "neutral" | "mixed" | "negative";
type Urgency = "low" | "medium" | "high" | "critical";

export type SeedItem = {
  dept: string;
  weeksAgo: number;
  channel: "text" | "voice" | "ocr";
  text: string; // English, redacted — what HR reads
  raw?: string; // original wording when not English / contains PII (kept only for identified submissions)
  language: string;
  summary: string;
  sentiment: Sentiment;
  score: number;
  emotions: string[];
  themes: string[];
  urgency: Urgency;
  flags: string[];
  action: string;
  category?: string;
  status?: "new" | "in_review" | "actioned" | "closed";
  response?: string;
  identified?: { name: string; email: string };
};

type Meta = [Sentiment, number, Urgency];
type Extra = Partial<Pick<SeedItem, "channel" | "raw" | "language" | "flags" | "category" | "status" | "response" | "identified">>;

function f(
  dept: string,
  weeksAgo: number,
  [sentiment, score, urgency]: Meta,
  themes: string[],
  emotions: string[],
  text: string,
  summary: string,
  action: string,
  extra: Extra = {},
): SeedItem {
  return {
    dept,
    weeksAgo,
    channel: extra.channel ?? "text",
    text,
    raw: extra.raw,
    language: extra.language ?? "English",
    summary,
    sentiment,
    score,
    emotions,
    themes,
    urgency,
    flags: extra.flags ?? [],
    action,
    category: extra.category,
    status: extra.status,
    response: extra.response,
    identified: extra.identified,
  };
}

const ENG = "Engineering";
const PRD = "Product";
const DES = "Design";
const SAL = "Sales";
const MKT = "Marketing";
const SUP = "Customer Support";
const OPS = "Operations";
const FIN = "Finance";
const HR = "People & HR";

export const SEED_ITEMS: SeedItem[] = [
  // ── Engineering: burnout arc (mild early, sharp in last 4 weeks) ──────────
  f(ENG, 11, ["neutral", 0.0, "low"], ["Workload & Burnout", "Tools & Resources"], ["tired"],
    "On-call this sprint was busier than usual because of the payments migration. Manageable, but we should look at alert noise before it gets worse.",
    "On-call load rose during the payments migration; alert noise should be reviewed.",
    "Ask the platform team to audit noisy alerts and share an on-call load report.", { status: "closed" }),
  f(ENG, 10, ["mixed", -0.1, "low"], ["Workload & Burnout", "Management & Leadership"], ["concerned"],
    "Sprint planning keeps adding scope mid-sprint. The team is coping, but it is starting to feel like the plan is just a suggestion.",
    "Scope is repeatedly added mid-sprint, eroding trust in planning.",
    "Encourage engineering managers to enforce a mid-sprint scope-change policy.", { status: "closed" }),
  f(ENG, 9, ["positive", 0.6, "low"], ["Team Culture", "Recognition"], ["proud", "grateful"],
    "Huge shout-out to the infra team for the zero-downtime database upgrade. The internal demo day where they walked us through it was brilliant.",
    "Praise for the infra team's zero-downtime upgrade and knowledge-sharing demo day.",
    "Recognise the infra team publicly and keep demo days as a regular ritual.", { status: "closed", category: "Appreciation" }),
  f(ENG, 8, ["negative", -0.4, "medium"], ["Workload & Burnout"], ["frustrated", "tired"],
    "I was paged four nights in a row last week. Most alerts were for things that auto-recovered. We need a proper on-call rotation with more people in it.",
    "Engineer paged four consecutive nights, mostly for self-healing alerts; rotation too small.",
    "Review on-call rotation size and suppress auto-recovering alerts.", { channel: "voice", status: "actioned",
      response: "Thanks for flagging. Platform leads have started an alert-noise audit and the rotation is being expanded from 5 to 8 engineers from next month." }),
  f(ENG, 7, ["positive", 0.5, "low"], ["Career Growth"], ["motivated"],
    "The new staff engineer career ladder is really clear. For the first time I understand what I need to do to get promoted.",
    "New staff-engineer career ladder is clear and motivating.",
    "Share the career ladder more widely and run Q&A sessions for other functions.", { category: "Appreciation", status: "closed" }),
  f(ENG, 6, ["negative", -0.5, "medium"], ["Workload & Burnout", "Management & Leadership"], ["stressed"],
    "Deadlines for the Q4 launch were set before engineering estimated anything. We are now expected to hit dates that were never realistic.",
    "Q4 launch deadlines were set without engineering estimates and feel unrealistic.",
    "Facilitate a re-planning session between product and engineering leadership for Q4 dates.", { status: "in_review" }),
  f(ENG, 5, ["negative", -0.5, "medium"], ["Workload & Burnout", "Work-Life Balance"], ["exhausted"],
    "Weekend deploys have become normal. Nobody says it is mandatory, but if you do not join you feel like you are letting the team down.",
    "Weekend deployments have become an unspoken expectation.",
    "Set a clear no-weekend-deploy default with an exception process.", { status: "in_review" }),
  f(ENG, 4, ["mixed", -0.2, "medium"], ["Tools & Resources", "Workload & Burnout"], ["frustrated"],
    "CI takes 45 minutes and flakes constantly. We lose hours every week re-running pipelines, which pushes everything else into the evening.",
    "Slow, flaky CI pipelines waste hours and push work into evenings.",
    "Fund a developer-productivity sprint targeting CI speed and flaky tests.", { status: "in_review" }),
  f(ENG, 3, ["negative", -0.7, "high"], ["Workload & Burnout", "Work-Life Balance"], ["exhausted", "anxious"],
    "I have not had a full weekend off in six weeks. On-call, the launch, and incident follow-ups are all landing on the same five people. I am running on empty.",
    "Engineer reports six weeks without a full weekend off; load concentrated on five people.",
    "Engineering leadership should redistribute launch and on-call load and offer recovery days.", { flags: ["burnout"], status: "in_review" }),
  f(ENG, 3, ["negative", -0.8, "high"], ["Workload & Burnout", "Management & Leadership"], ["burned out", "resentful"],
    "My manager [NAME] keeps saying 'just this sprint' but it has been every sprint since August. Two people on my team have started interviewing elsewhere.",
    "Repeated 'just this sprint' crunch since August; teammates are interviewing elsewhere.",
    "Hold skip-level conversations in the team and agree a sustainable delivery plan.",
    { raw: "My manager Arjun keeps saying 'just this sprint' but it has been every sprint since August. Two people on my team have started interviewing elsewhere.", flags: ["burnout", "attrition_risk"], status: "new" }),
  f(ENG, 2, ["negative", -0.8, "high"], ["Workload & Burnout", "Work-Life Balance"], ["exhausted", "hopeless"],
    "Got paged at 3am three times this week for the same flaky alert. I asked twice for it to be fixed. I dread my phone now.",
    "Repeated 3am pages for a known flaky alert; engineer dreads being on call.",
    "Escalate the flaky alert fix as P1 and review on-call compensation and recovery time.", { channel: "voice", flags: ["burnout", "mental_health"], status: "new" }),
  f(ENG, 2, ["negative", -0.6, "high"], ["Workload & Burnout", "Career Growth"], ["demotivated"],
    "All the interesting roadmap work was paused for the launch. I spend my days firefighting and have not written meaningful code in a month. I am starting to look around.",
    "Firefighting has replaced meaningful work for a month; engineer considering leaving.",
    "Protect a share of sprint capacity for planned work and discuss growth goals in 1:1s.", { flags: ["attrition_risk"], status: "new" }),
  f(ENG, 1, ["negative", -0.9, "high"], ["Workload & Burnout", "Work-Life Balance"], ["overwhelmed", "anxious"],
    "I am working 12-hour days and still falling behind. I have started having trouble sleeping. I do not know how long I can keep this pace up.",
    "Engineer working 12-hour days with sleep problems and doubts about sustainability.",
    "Reach out confidentially with EAP support and reduce this team's load immediately.", { flags: ["burnout", "mental_health"], status: "new" }),
  f(ENG, 1, ["negative", -0.7, "high"], ["Workload & Burnout", "Communication"], ["frustrated"],
    "Leadership keeps praising the launch in all-hands but nobody acknowledges what it is costing the team. The disconnect is demoralising.",
    "Leadership celebrates the launch without acknowledging its toll on the team.",
    "Brief leadership on workload data and encourage an honest acknowledgement at the next all-hands.", { flags: ["burnout"], status: "new" }),
  f(ENG, 1, ["negative", -0.6, "high"], ["Workload & Burnout"], ["tired", "irritated"],
    "The on-call rotation expansion that was promised has not happened yet. Same five people, more services.",
    "Promised on-call rotation expansion has not happened; load keeps growing.",
    "Follow up on the rotation expansion commitment and publish a date.", { status: "new" }),
  f(ENG, 0, ["negative", -0.8, "high"], ["Workload & Burnout", "Management & Leadership"], ["burned out"],
    "Three people on the payments team are on the edge. We need a real break after the launch, not another 'stretch goal'.",
    "Payments team members near breaking point; a real post-launch break is needed.",
    "Plan a post-launch recovery period and freeze new commitments for the payments team.", { flags: ["burnout", "attrition_risk"], status: "new" }),
  f(ENG, 0, ["negative", -0.7, "high"], ["Workload & Burnout", "Compensation & Benefits"], ["undervalued"],
    "We are not compensated for on-call at all. Other companies pay an on-call allowance. Being woken up for free every week is not sustainable.",
    "No on-call compensation; engineers feel undervalued compared with the market.",
    "Benchmark on-call allowances and propose a policy to leadership.", { status: "new", category: "Suggestion" }),
  f(ENG, 0, ["negative", -0.6, "high"], ["Workload & Burnout"], ["exhausted"],
    "Hello, for the past month we have been working late every single night. The team is exhausted and it feels like nobody cares.",
    "Team has worked late every night for a month and feels no one cares.",
    "Check in with the team lead and set explicit limits on after-hours work.",
    {
      language: "Hindi",
      raw: "नमस्ते, पिछले एक महीने से हर रात देर तक काम कर रहे हैं। टीम थक चुकी है और किसी को परवाह नहीं लगती।",
      flags: ["burnout"],
      status: "new",
    }),
  f(ENG, 0, ["mixed", -0.1, "medium"], ["Team Culture", "Workload & Burnout"], ["tired", "loyal"],
    "Honestly the team itself is great. We look out for each other. But we cannot keep covering for a staffing gap that leadership has known about for months.",
    "Strong team cohesion, but a long-known staffing gap is being covered by overwork.",
    "Prioritise approved backfills for the engineering team.", { channel: "voice", status: "new" }),
  f(ENG, 2, ["positive", 0.5, "low"], ["Recognition", "Team Culture"], ["grateful"],
    "My manager blocked out a no-meeting Friday for us after the last incident. Small thing, but it made a real difference.",
    "Manager's no-meeting Friday after an incident was appreciated.",
    "Share this practice with other engineering managers as a recovery norm.", { category: "Appreciation", status: "closed" }),

  // ── Sales: commission plan confusion (weeks 2–7) ──────────────────────────
  f(SAL, 10, ["positive", 0.6, "low"], ["Recognition", "Team Culture"], ["excited"],
    "The Q2 President's Club trip announcement really fired up the team. Nice to see top performers rewarded.",
    "Q2 President's Club trip announcement motivated the sales team.",
    "Keep recognition programmes visible and inclusive of support roles.", { category: "Appreciation", status: "closed" }),
  f(SAL, 9, ["neutral", 0.0, "low"], ["Tools & Resources"], ["neutral"],
    "The CRM is slow on mobile. Not a huge deal but it makes logging calls after meetings annoying.",
    "CRM mobile performance makes logging calls tedious.",
    "Pass mobile CRM performance feedback to RevOps.", { status: "closed" }),
  f(SAL, 7, ["negative", -0.5, "medium"], ["Compensation & Benefits", "Communication"], ["confused", "worried"],
    "The new commission plan was announced in a single slide with no examples. Nobody on my team can calculate what they will actually earn this quarter.",
    "New commission plan announced without examples; reps cannot estimate earnings.",
    "Publish worked examples and a calculator for the new commission plan.", { status: "actioned",
      response: "You were not alone in this. Finance and Sales Ops have published a commission calculator and worked examples on the intranet, and will run two live Q&A sessions this week." }),
  f(SAL, 6, ["negative", -0.6, "medium"], ["Compensation & Benefits"], ["anxious", "frustrated"],
    "Accelerators now kick in at 120% instead of 100%. For most of us that is a pay cut dressed up as a new plan.",
    "Accelerator threshold moved from 100% to 120%, perceived as an effective pay cut.",
    "Share the rationale and modelling behind the accelerator change with the sales team.", { status: "in_review" }),
  f(SAL, 6, ["negative", -0.5, "medium"], ["Compensation & Benefits", "Management & Leadership"], ["distrustful"],
    "When we asked our regional director about the plan, the answer was 'trust the process'. That is not an answer when rent depends on it.",
    "Leadership responses to commission questions feel dismissive.",
    "Coach sales leaders on explaining the plan and handling compensation questions.", { channel: "voice", status: "in_review" }),
  f(SAL, 5, ["negative", -0.7, "high"], ["Compensation & Benefits", "Career Growth"], ["demotivated"],
    "Two of our best closers have already told me they are talking to competitors because of the new plan. We will lose them before Q4.",
    "Top sales performers reportedly talking to competitors over the commission plan.",
    "Run retention conversations with top performers and review plan competitiveness.", { flags: ["attrition_risk"], status: "in_review" }),
  f(SAL, 5, ["mixed", -0.2, "medium"], ["Compensation & Benefits", "Communication"], ["uncertain"],
    "New commission plan: I understand the company needs to change, but nobody explained how it affects customers that were already in the pipeline.",
    "Unclear how the new commission plan treats deals already in the pipeline.",
    "Clarify grandfathering rules for in-flight deals in writing.",
    {
      language: "Spanish",
      raw: "Plan de comisiones nuevo: entiendo que la empresa necesita cambiar, pero nadie nos explicó cómo afecta a los clientes que ya estaban en el pipeline.",
      status: "actioned",
      response: "Good question. In-flight deals created before 1 September are paid on the old plan. This is now in the FAQ.",
    }),
  f(SAL, 4, ["negative", -0.5, "medium"], ["Compensation & Benefits"], ["frustrated"],
    "My commission statement for August was wrong again. It took three emails to get a reply from finance.",
    "Commission statements contain errors and finance responses are slow.",
    "Set an SLA for commission queries and audit August statements.", { status: "in_review" }),
  f(SAL, 3, ["mixed", 0.1, "low"], ["Compensation & Benefits", "Communication"], ["relieved"],
    "The commission calculator helped a lot. Still not happy about the 120% threshold, but at least I can plan now.",
    "Commission calculator improved clarity, though the threshold remains unpopular.",
    "Keep the calculator updated and gather feedback on the threshold for the next plan review.", { status: "closed" }),
  f(SAL, 2, ["negative", -0.4, "medium"], ["Workload & Burnout", "Compensation & Benefits"], ["pressured"],
    "Quotas went up 30% while territories got smaller. The maths does not work unless the market doubles.",
    "Quotas rose 30% while territories shrank, making targets feel unreachable.",
    "Review quota-setting methodology with Sales Ops and share assumptions.", { status: "new" }),
  f(SAL, 1, ["positive", 0.4, "low"], ["Team Culture"], ["supported"],
    "Our new team lead does weekly deal reviews that actually help instead of feeling like interrogations. Big improvement.",
    "New sales team lead runs helpful, supportive deal reviews.",
    "Recognise the team lead and share their deal-review format.", { category: "Appreciation", status: "new" }),
  f(SAL, 0, ["negative", -0.5, "medium"], ["Tools & Resources"], ["annoyed"],
    "We still do not have a proper sales enablement library. I spend hours hunting for the latest deck and case studies.",
    "No central sales enablement library; reps waste time hunting for materials.",
    "Ask Marketing and Sales Ops to create a single enablement hub.", { category: "Suggestion", status: "new" }),

  // ── Customer Support: praising new tooling ────────────────────────────────
  f(SUP, 11, ["negative", -0.6, "medium"], ["Tools & Resources", "Workload & Burnout"], ["frustrated", "tired"],
    "The old ticketing tool crashes daily. We copy-paste customer details between three systems. Handle times are terrible and customers can tell.",
    "Legacy ticketing tool crashes daily and forces manual copy-paste between systems.",
    "Prioritise the helpdesk tooling replacement.", { status: "closed" }),
  f(SUP, 9, ["negative", -0.4, "medium"], ["Workload & Burnout"], ["stressed"],
    "Ticket backlog is over 800. We are asked to close faster but the tools fight us every step.",
    "Support backlog above 800 tickets with tools slowing resolution.",
    "Provide temporary backlog support and fast-track new tooling.", { status: "closed" }),
  f(SUP, 6, ["positive", 0.7, "low"], ["Tools & Resources"], ["relieved", "happy"],
    "The new helpdesk rollout is a game changer. Macros, customer history in one place, and it does not crash. Thank you for listening!",
    "New helpdesk tool praised for macros, unified history and stability.",
    "Share the rollout success with leadership and thank the implementation team.", { category: "Appreciation", status: "closed",
      response: "Thank you! We have passed this on to the IT and Support Ops folks who led the rollout." }),
  f(SUP, 5, ["positive", 0.8, "low"], ["Tools & Resources", "Recognition"], ["proud", "grateful"],
    "Our CSAT went from 78 to 89 in a month after the new tools. It feels amazing to actually solve problems instead of fighting software.",
    "CSAT rose from 78 to 89 after new support tooling.",
    "Celebrate the CSAT improvement with the support team publicly.", { category: "Appreciation", status: "closed" }),
  f(SUP, 4, ["positive", 0.6, "low"], ["Tools & Resources", "Onboarding & Training"], ["confident"],
    "The AI-suggested replies in the new helpdesk save me so much time. The training sessions were short and actually useful.",
    "AI reply suggestions and concise training on the new helpdesk save time.",
    "Reuse the helpdesk training format for other tool rollouts.", { channel: "voice", category: "Appreciation", status: "closed" }),
  f(SUP, 3, ["positive", 0.7, "low"], ["Team Culture", "Recognition"], ["happy"],
    "Since the new tools arrived, work has become much easier. Our team lead supports us really well.",
    "Work became much easier with the new tools, and the team lead is very supportive.",
    "Recognise the support team lead and the tooling project.",
    {
      language: "Tamil",
      raw: "புதிய கருவிகள் வந்த பிறகு வேலை மிகவும் எளிதாகிவிட்டது. எங்கள் குழுத் தலைவர் எங்களை நன்றாக ஆதரிக்கிறார்.",
      category: "Appreciation",
      status: "closed",
    }),
  f(SUP, 2, ["mixed", 0.1, "low"], ["Tools & Resources", "Career Growth"], ["hopeful"],
    "Tools are great now. Next step: a clear path from Tier 1 to Tier 2 or to other teams. A lot of us want to grow here.",
    "Support agents now want a clear career path beyond Tier 1.",
    "Define and publish a support career ladder with internal mobility options.", { category: "Suggestion", status: "in_review" }),
  f(SUP, 1, ["positive", 0.6, "low"], ["Tools & Resources", "Work-Life Balance"], ["calm"],
    "For the first time in a year I am logging off on time. The backlog is under control.",
    "Support agent now logs off on time as backlog is under control.",
    "Track support workload metrics to sustain the improvement.", { category: "Appreciation", status: "new" }),
  f(SUP, 1, ["negative", -0.5, "medium"], ["Compensation & Benefits"], ["undervalued"],
    "Support salaries are well below market. With the new tools we handle far more volume, but pay has not moved.",
    "Support pay below market despite higher productivity.",
    "Benchmark support salaries and review in the next compensation cycle.", { status: "new" }),
  f(SUP, 0, ["negative", -0.9, "critical"], ["Workplace Safety", "Diversity & Inclusion"], ["upset", "unsafe"],
    "A senior colleague keeps making comments about my appearance and asked me out again after I clearly said no. I have started avoiding the late shift because of him.",
    "Employee reports repeated unwanted comments and advances from a senior colleague.",
    "Open a confidential harassment investigation immediately and offer support and shift flexibility.",
    { flags: ["harassment", "safety"], status: "in_review", category: "Report an issue" }),

  // ── Hybrid work debate (weeks 3–8, all departments) ───────────────────────
  f(PRD, 8, ["negative", -0.5, "medium"], ["Remote & Hybrid Work", "Communication"], ["frustrated"],
    "The 3-days-in-office mandate was announced with two weeks' notice and no explanation. Many of us moved further away during remote work.",
    "Three-day office mandate announced abruptly without rationale.",
    "Share the reasoning behind the hybrid policy and offer transition support.", { status: "actioned",
      response: "Leadership has shared a written rationale, and the policy now includes a 6-week transition period plus exceptions for long commutes." }),
  f(ENG, 8, ["negative", -0.5, "medium"], ["Remote & Hybrid Work", "Work-Life Balance"], ["annoyed"],
    "I commute 90 minutes each way to sit on video calls with people in other offices. Office days are my least productive days.",
    "Long commutes to attend video calls make office days unproductive.",
    "Coordinate team anchor days so in-office time is spent together.", { status: "closed" }),
  f(DES, 7, ["positive", 0.5, "low"], ["Remote & Hybrid Work", "Team Culture"], ["energised"],
    "Honestly I love being back in the studio. Whiteboarding with the team is so much faster than Figma comments.",
    "Designer enjoys in-person collaboration after the return to office.",
    "Highlight collaborative in-office rituals that teams find valuable.", { status: "closed", category: "Appreciation" }),
  f(MKT, 7, ["mixed", -0.1, "medium"], ["Remote & Hybrid Work"], ["ambivalent"],
    "Being in the office is nice for brainstorming, but three fixed days is too rigid. Let teams pick their own anchor days.",
    "Office time helps brainstorming but fixed three days is too rigid.",
    "Pilot team-chosen anchor days within the hybrid policy.", { category: "Suggestion", status: "actioned",
      response: "Teams can now choose their own two anchor days plus one flexible day. Thanks for the suggestion." }),
  f(FIN, 6, ["negative", -0.4, "medium"], ["Remote & Hybrid Work", "Diversity & Inclusion"], ["worried"],
    "As a parent the new office days make school pickup impossible. It feels like the policy was written for people without caring responsibilities.",
    "Hybrid policy conflicts with caregiving; parents feel overlooked.",
    "Add caregiver flexibility options to the hybrid policy.", { flags: ["attrition_risk"], status: "actioned",
      response: "We have added core hours (10am–4pm) on office days and a caregiver exception process." }),
  f(OPS, 6, ["neutral", 0.1, "low"], ["Remote & Hybrid Work", "Facilities"], ["neutral"],
    "Operations was always in the office, so the policy does not change much for us. But now the canteen and parking are packed.",
    "Office crowding (canteen, parking) increased with the hybrid policy.",
    "Review canteen capacity and parking allocation for peak office days.", { status: "closed" }),
  f(PRD, 5, ["mixed", 0.0, "medium"], ["Remote & Hybrid Work", "Facilities"], ["mixed"],
    "Office days would be better if there were enough meeting rooms. Half my day is spent looking for a quiet place to take calls.",
    "Insufficient meeting rooms make office days inefficient.",
    "Add phone booths and bookable quiet rooms.", { category: "Suggestion", status: "in_review" }),
  f(ENG, 5, ["negative", -0.6, "high"], ["Remote & Hybrid Work", "Career Growth"], ["resentful"],
    "I was hired fully remote. Now I am told remote workers will be 'considered' for promotion differently. That feels like a bait and switch.",
    "Remote-hired employee fears promotion penalties under the new policy.",
    "Clarify in writing that promotion criteria are location-neutral.", { flags: ["attrition_risk"], status: "in_review" }),
  f(MKT, 4, ["positive", 0.4, "low"], ["Remote & Hybrid Work", "Team Culture"], ["connected"],
    "Our Tuesday team lunches in the office have really brought the team together. New joiners especially benefit.",
    "Team lunches on office days improve cohesion, especially for new joiners.",
    "Encourage teams to pair office days with social rituals.", { category: "Appreciation", status: "closed" }),
  f(DES, 4, ["negative", -0.3, "medium"], ["Remote & Hybrid Work", "Facilities"], ["distracted"],
    "The open-plan floor is too loud for focused design work. Office days are great for crits, terrible for deep work.",
    "Open-plan office is too noisy for focused design work.",
    "Designate quiet zones for focus work on office days.", { category: "Suggestion", status: "in_review" }),
  f(HR, 3, ["mixed", 0.0, "low"], ["Remote & Hybrid Work", "Communication"], ["thoughtful"],
    "We are fielding lots of hybrid-policy exception requests with no clear criteria. We need a consistent framework so managers do not decide ad hoc.",
    "Hybrid exception requests are handled inconsistently without clear criteria.",
    "Publish a hybrid exception framework for managers.", { status: "in_review" }),
  f(SAL, 3, ["neutral", 0.2, "low"], ["Remote & Hybrid Work"], ["indifferent"],
    "Sales is on the road most of the week anyway. Please do not count client-site days against our office days.",
    "Client-site days should count toward office attendance for sales.",
    "Clarify that client-site days count as in-office days.", { category: "Suggestion", status: "actioned",
      response: "Confirmed: client-site days count as office days. The policy page has been updated." }),

  // ── Critical & sensitive items ────────────────────────────────────────────
  f(OPS, 9, ["negative", -0.8, "critical"], ["Workplace Safety"], ["scared", "angry"],
    "The forklift in warehouse bay 3 has had faulty brakes for two weeks. It was reported but it is still being used. Someone is going to get hurt.",
    "Forklift with faulty brakes is still in use despite being reported.",
    "Take the forklift out of service immediately and audit equipment maintenance reporting.",
    { channel: "ocr", flags: ["safety"], status: "actioned", category: "Report an issue",
      response: "The forklift was taken out of service the same day and repaired. We have also introduced a daily equipment checklist." }),
  f(FIN, 7, ["negative", -0.8, "critical"], ["Diversity & Inclusion", "Career Growth"], ["hurt", "discouraged"],
    "I have been passed over for the team lead role twice in favour of less experienced men. When I asked why, I was told I am 'not assertive enough'.",
    "Employee alleges gendered bias in team-lead promotion decisions.",
    "Review recent promotion decisions for bias and open a confidential conversation with the employee.",
    { flags: ["discrimination", "attrition_risk"], status: "in_review", category: "Report an issue" }),
  f(OPS, 4, ["negative", -0.7, "critical"], ["Workplace Safety", "Facilities"], ["worried"],
    "The fire exit on the 2nd floor is blocked by stacked boxes most days. The last fire drill was over a year ago.",
    "Second-floor fire exit routinely blocked; no fire drill in over a year.",
    "Clear the fire exit today and schedule a fire drill and a facilities safety audit.",
    { channel: "ocr", flags: ["safety"], status: "actioned", category: "Report an issue",
      response: "The exit has been cleared, weekly checks assigned to facilities, and a fire drill is scheduled for next Thursday." }),
  f(MKT, 2, ["negative", -0.8, "critical"], ["Management & Leadership", "Diversity & Inclusion"], ["humiliated"],
    "My manager regularly mocks my accent in meetings and others laugh along. I have stopped speaking up in team calls.",
    "Employee reports a manager mocking their accent in meetings.",
    "Start a confidential investigation and brief the manager's leader on respectful conduct expectations.",
    { flags: ["discrimination", "harassment"], status: "in_review", category: "Report an issue" }),
  f(FIN, 1, ["negative", -0.7, "critical"], ["Management & Leadership"], ["uneasy"],
    "I was asked to backdate approval on several vendor invoices before the audit. I am uncomfortable and do not know who to tell.",
    "Employee asked to backdate vendor invoice approvals before an audit.",
    "Route to the ethics/compliance officer confidentially and protect the reporter from retaliation.",
    { flags: ["ethics"], status: "new", category: "Report an issue" }),
  f(ENG, 0, ["negative", -0.9, "critical"], ["Workload & Burnout", "Management & Leadership"], ["hopeless", "overwhelmed"],
    "I am not okay. Between the launch and on-call I feel like I am drowning and I have had some really dark thoughts this week. I do not know who else to tell.",
    "Employee describes feeling overwhelmed with dark thoughts due to workload.",
    "Share mental-health and EAP crisis resources immediately and have HR reach out through a confidential channel.",
    { flags: ["mental_health", "burnout"], status: "new" }),

  // ── Product ───────────────────────────────────────────────────────────────
  f(PRD, 11, ["positive", 0.5, "low"], ["Team Culture", "Communication"], ["motivated"],
    "The quarterly strategy offsite gave everyone real clarity on priorities. Please keep doing these.",
    "Strategy offsite gave product team clear priorities.",
    "Continue quarterly offsites and share summaries with adjacent teams.", { category: "Appreciation", status: "closed" }),
  f(PRD, 9, ["mixed", -0.1, "low"], ["Communication", "Management & Leadership"], ["confused"],
    "Roadmap priorities changed three times this quarter and we heard about two of them in Slack threads.",
    "Roadmap changed repeatedly and was communicated informally.",
    "Create a single roadmap changelog with owners and dates.", { status: "closed" }),
  f(PRD, 6, ["negative", -0.4, "medium"], ["Management & Leadership", "Workload & Burnout"], ["pressured"],
    "We committed Q4 dates to customers before engineering sized the work. Now product is stuck between sales promises and a burned-out eng team.",
    "Product caught between customer commitments and engineering capacity.",
    "Introduce a sizing gate before customer commitments.", { status: "in_review" }),
  f(PRD, 4, ["positive", 0.5, "low"], ["Career Growth", "Onboarding & Training"], ["grateful"],
    "The PM mentorship programme paired me with a senior PM and it has been fantastic for my growth.",
    "PM mentorship programme is valuable for career growth.",
    "Expand the mentorship programme to more functions.", { category: "Appreciation", status: "closed" }),
  f(PRD, 2, ["negative", -0.5, "medium"], ["Communication"], ["frustrated"],
    "Decisions get made in meetings I am not invited to and I find out after the fact. PMs are accountable for outcomes but excluded from key decisions.",
    "PMs excluded from key decisions they are accountable for.",
    "Clarify decision rights (RACI) between product and leadership.", { status: "new" }),
  f(PRD, 0, ["mixed", -0.2, "medium"], ["Workload & Burnout", "Team Culture"], ["worried"],
    "I can see how exhausted our engineers are. We should cut scope for the next release instead of asking for more overtime.",
    "PM concerned about engineer exhaustion, recommends scope cuts over overtime.",
    "Facilitate a scope-reduction decision for the next release.", { category: "Suggestion", status: "new" }),

  // ── Design ────────────────────────────────────────────────────────────────
  f(DES, 10, ["negative", -0.3, "low"], ["Tools & Resources"], ["annoyed"],
    "We only have five Figma editor seats for eight designers. People share logins which is messy and against policy.",
    "Not enough Figma seats; designers share logins.",
    "Purchase additional Figma editor seats.", { status: "actioned", response: "Three additional Figma seats have been purchased. Please stop sharing logins." }),
  f(DES, 8, ["positive", 0.6, "low"], ["Recognition"], ["proud"],
    "The design system work got a shout-out from the CEO at all-hands. It meant a lot to the team.",
    "CEO recognition of design system work boosted morale.",
    "Keep recognising cross-team enablers at all-hands.", { category: "Appreciation", status: "closed" }),
  f(DES, 5, ["mixed", -0.1, "low"], ["Career Growth"], ["uncertain"],
    "There is no senior designer or design manager track here. I am not sure where I go next.",
    "No clear senior or management track for designers.",
    "Define a design career framework with IC and management tracks.", { category: "Suggestion", status: "in_review" }),
  f(DES, 3, ["negative", -0.4, "medium"], ["Communication", "Management & Leadership"], ["frustrated"],
    "Design is brought in after decisions are made and asked to 'make it pretty'. We want to be involved in discovery.",
    "Design is involved too late in product decisions.",
    "Include design in discovery and planning rituals by default.", { status: "new" }),
  f(DES, 1, ["positive", 0.5, "low"], ["Team Culture"], ["happy"],
    "Weekly design crits have become the best hour of my week. Supportive and sharp.",
    "Weekly design critiques are valued as supportive and useful.",
    "Share the crit format with other teams.", { category: "Appreciation", status: "new" }),

  // ── Marketing ─────────────────────────────────────────────────────────────
  f(MKT, 11, ["neutral", 0.0, "low"], ["Tools & Resources"], ["neutral"],
    "Our marketing automation tool and CRM do not sync properly. Lead data is often a day late.",
    "Marketing automation and CRM sync delays lead data.",
    "Ask RevOps to fix the marketing–CRM integration.", { status: "closed" }),
  f(MKT, 9, ["negative", -0.4, "medium"], ["Workload & Burnout"], ["stretched"],
    "We lost two people and were not allowed to backfill, but the campaign calendar did not shrink.",
    "Marketing lost two people without backfill but workload is unchanged.",
    "Reprioritise the campaign calendar or approve backfills.", { status: "closed" }),
  f(MKT, 5, ["positive", 0.6, "low"], ["Recognition", "Team Culture"], ["proud"],
    "The product launch campaign smashed its targets and our head of marketing made sure every contributor was named. Great leadership.",
    "Leader credited every contributor after a successful campaign.",
    "Highlight inclusive recognition as a leadership behaviour.", { category: "Appreciation", status: "closed" }),
  f(MKT, 3, ["mixed", 0.0, "low"], ["Onboarding & Training"], ["curious"],
    "Would love a proper training budget for AI tools. Everyone is experimenting on their own with no guidance.",
    "Marketing wants structured training on AI tools.",
    "Offer an AI tools training programme with usage guidelines.", { category: "Suggestion", status: "in_review" }),
  f(MKT, 1, ["negative", -0.3, "low"], ["Communication"], ["annoyed"],
    "Sales keeps saying marketing leads are bad but will not share which ones or why. We need a shared lead-quality definition.",
    "Marketing and sales disagree on lead quality without shared definitions.",
    "Facilitate a joint sales–marketing lead-quality agreement.", { category: "Suggestion", status: "new" }),
  f(MKT, 0, ["positive", 0.4, "low"], ["Work-Life Balance"], ["relaxed"],
    "The summer Fridays pilot was great. Please make it permanent.",
    "Summer Fridays pilot was popular; employee asks to make it permanent.",
    "Evaluate making the summer Fridays pilot permanent.", { category: "Suggestion", status: "new" }),

  // ── Operations ────────────────────────────────────────────────────────────
  f(OPS, 10, ["negative", -0.4, "medium"], ["Workplace Safety", "Facilities"], ["uncomfortable"],
    "The warehouse gets extremely hot in the afternoons. Two people felt dizzy last week. We need proper ventilation.",
    "Warehouse overheating caused dizziness; ventilation needed.",
    "Install cooling/ventilation and adjust shift breaks during hot hours.",
    { channel: "ocr", flags: ["safety"], status: "actioned", response: "Industrial fans have been installed and extra water breaks are scheduled in the afternoon." }),
  f(OPS, 8, ["positive", 0.5, "low"], ["Recognition"], ["appreciated"],
    "Thank you for the Diwali bonus and the celebration at the warehouse. It felt good to be included.",
    "Warehouse staff appreciated the festive bonus and celebration.",
    "Keep festivals inclusive of frontline teams.", { channel: "ocr", category: "Appreciation", status: "closed" }),
  f(OPS, 7, ["negative", -0.5, "medium"], ["Management & Leadership", "Communication"], ["ignored"],
    "Shift schedules are posted the night before. Impossible to plan anything in our personal lives.",
    "Shift schedules published too late to plan personal life.",
    "Publish shift schedules at least one week in advance.",
    { channel: "ocr", status: "actioned", response: "Shift rosters will now be published every Friday for the following two weeks." }),
  f(OPS, 5, ["negative", -0.4, "medium"], ["Compensation & Benefits"], ["unfair"],
    "Overtime pay for weekend shifts is processed two months late. Many of us depend on it.",
    "Weekend overtime pay is processed two months late.",
    "Fix overtime payroll timing with Finance.", { channel: "ocr", status: "in_review" }),
  f(OPS, 3, ["mixed", 0.0, "low"], ["Onboarding & Training", "Workplace Safety"], ["hopeful"],
    "New staff are not being given proper safety training. If the training were given in Kannada, everyone would understand it.",
    "New staff are not getting proper safety training; training in Kannada would help everyone understand.",
    "Offer safety induction in Kannada and other local languages.",
    {
      language: "Kannada",
      channel: "voice",
      raw: "ಹೊಸ ಸಿಬ್ಬಂದಿಗೆ ಸುರಕ್ಷತಾ ತರಬೇತಿ ಸರಿಯಾಗಿ ಕೊಡುತ್ತಿಲ್ಲ. ಕನ್ನಡದಲ್ಲಿ ತರಬೇತಿ ಕೊಟ್ಟರೆ ಎಲ್ಲರಿಗೂ ಅರ್ಥವಾಗುತ್ತದೆ.",
      category: "Suggestion",
      status: "in_review",
      identified: { name: "Manjunath K", email: "manjunath.k@acme.example" },
    }),
  f(OPS, 1, ["positive", 0.5, "low"], ["Workplace Safety", "Management & Leadership"], ["reassured"],
    "After the fire exit issue, facilities now does weekly checks and the supervisor walks us through them. Feels much safer.",
    "Weekly facilities safety checks have improved perceived safety.",
    "Continue weekly checks and share results with staff.", { channel: "ocr", category: "Appreciation", status: "new" }),
  f(OPS, 0, ["negative", -0.4, "medium"], ["Tools & Resources"], ["frustrated"],
    "Half the barcode scanners have dead batteries by mid-shift. We lose a lot of time waiting for chargers.",
    "Barcode scanner batteries die mid-shift, slowing work.",
    "Procure spare batteries and charging stations for scanners.", { channel: "ocr", status: "new" }),

  // ── Finance ───────────────────────────────────────────────────────────────
  f(FIN, 10, ["mixed", 0.0, "low"], ["Tools & Resources"], ["tired"],
    "Month-end close still relies on a dozen spreadsheets. We could automate most of it.",
    "Month-end close depends on manual spreadsheets.",
    "Scope finance automation for month-end close.", { category: "Suggestion", status: "closed" }),
  f(FIN, 8, ["negative", -0.4, "medium"], ["Workload & Burnout"], ["stressed"],
    "Close week means 14-hour days for the whole team. It is every month.",
    "Month-end close causes 14-hour days monthly.",
    "Invest in close automation and temporary support during close.", { status: "closed" }),
  f(FIN, 5, ["positive", 0.5, "low"], ["Onboarding & Training"], ["confident"],
    "The CFO's lunch-and-learn series on reading P&Ls was brilliant. Even people outside finance joined.",
    "CFO's lunch-and-learn series was popular across teams.",
    "Continue and record the lunch-and-learn series.", { category: "Appreciation", status: "closed" }),
  f(FIN, 3, ["mixed", -0.1, "low"], ["Communication"], ["confused"],
    "Budget approvals take weeks and nobody knows where requests are stuck. A simple tracker would help.",
    "Budget approvals are slow and opaque.",
    "Introduce a budget request tracker with status visibility.", { category: "Suggestion", status: "in_review" }),
  f(FIN, 0, ["neutral", 0.1, "low"], ["Remote & Hybrid Work"], ["neutral"],
    "The core-hours change to the office policy works well for me. Thanks for listening to parents.",
    "Core-hours adjustment to the hybrid policy works well for parents.",
    "Share the positive impact of core hours with leadership.", { category: "Appreciation", status: "new" }),

  // ── People & HR ───────────────────────────────────────────────────────────
  f(HR, 9, ["mixed", 0.0, "low"], ["Tools & Resources"], ["busy"],
    "We collect engagement data in three different tools and none of them talk to each other.",
    "Engagement data is fragmented across three HR tools.",
    "Consolidate engagement tooling.", { category: "Suggestion", status: "closed" }),
  f(HR, 6, ["negative", -0.4, "medium"], ["Workload & Burnout"], ["stretched"],
    "HRBPs are covering 150+ employees each. We cannot do proactive work, only firefighting.",
    "HR business partners overloaded with 150+ employees each.",
    "Review HRBP coverage ratios and hiring plan.", { status: "in_review" }),
  f(HR, 2, ["positive", 0.6, "low"], ["Recognition", "Team Culture"], ["encouraged"],
    "Seeing employees get responses to their feedback has changed the tone of conversations. People feel heard.",
    "Closing the loop on feedback has improved employee trust.",
    "Keep response times short and publicise 'you said, we did' updates.", { category: "Appreciation", status: "new" }),
  f(HR, 0, ["mixed", 0.0, "medium"], ["Onboarding & Training", "Management & Leadership"], ["concerned"],
    "Many first-time managers have had no management training at all. A lot of the issues we see trace back to that.",
    "First-time managers lack management training.",
    "Launch a first-time manager training programme.", { category: "Suggestion", status: "new" }),

  // ── Onboarding, recognition & misc across teams ───────────────────────────
  f(ENG, 10, ["positive", 0.5, "low"], ["Onboarding & Training"], ["welcomed"],
    "My onboarding buddy was great and the dev environment setup guide actually worked on day one.",
    "Smooth engineering onboarding with a helpful buddy and working setup guide.",
    "Keep the buddy programme and setup guide maintained.", { category: "Appreciation", status: "closed" }),
  f(SUP, 8, ["negative", -0.3, "low"], ["Onboarding & Training"], ["lost"],
    "I joined three weeks ago and still do not have access to half the systems I need.",
    "New joiner lacks system access three weeks in.",
    "Create an access checklist owned by IT for new joiners.", { status: "closed" }),
  f(SAL, 8, ["positive", 0.4, "low"], ["Onboarding & Training"], ["confident"],
    "The sales bootcamp for new hires was intense but I felt ready to take calls by week two.",
    "Sales bootcamp prepared new hires quickly.",
    "Continue the bootcamp and gather new-hire ramp metrics.", { category: "Appreciation", status: "closed" }),
  f(PRD, 10, ["neutral", 0.0, "low"], ["Facilities"], ["neutral"],
    "Could we get better coffee on the 4th floor? The machine has been broken for a week.",
    "Broken coffee machine on the 4th floor.",
    "Ask facilities to repair the coffee machine.", { category: "Suggestion", status: "closed" }),
  f(MKT, 8, ["positive", 0.5, "low"], ["Diversity & Inclusion", "Team Culture"], ["included"],
    "The Pride month events were thoughtful and not just a logo change. Felt genuinely supported.",
    "Pride month events felt genuine and supportive.",
    "Continue employee-led inclusion events with real budget.", { category: "Appreciation", status: "closed" }),
  f(FIN, 9, ["negative", -0.3, "low"], ["Compensation & Benefits"], ["disappointed"],
    "The health insurance doesn't cover my parents. Many colleagues have asked for a parental add-on option.",
    "Employees want a parental health insurance add-on.",
    "Get quotes for a parental add-on to the health plan.", { category: "Suggestion", status: "actioned",
      response: "An optional parental add-on will be available from the next policy renewal in January." }),
  f(OPS, 11, ["negative", -0.4, "medium"], ["Facilities", "Workplace Safety"], ["uncomfortable"],
    "The women's restroom near the loading dock has no lock and poor lighting. It feels unsafe during night shifts.",
    "Restroom near loading dock lacks lock and lighting, unsafe at night.",
    "Fix the lock and lighting urgently and review night-shift facilities.",
    { channel: "ocr", flags: ["safety"], status: "closed", response: "Locks and lighting were fixed within 48 hours. Thank you for raising it." }),
  f(DES, 9, ["neutral", 0.1, "low"], ["Remote & Hybrid Work"], ["neutral"],
    "Remote collaboration works fine for us with good async docs. Please do not force a change for its own sake.",
    "Design team finds async remote collaboration effective.",
    "Consider team-level flexibility when designing hybrid policy.", { status: "closed" }),
  f(SUP, 7, ["negative", -0.5, "high"], ["Management & Leadership", "Workload & Burnout"], ["drained"],
    "Abusive customer calls are escalating and there is no policy to let us end them. We just have to take it.",
    "Support agents lack a policy to end abusive customer calls.",
    "Introduce an abusive-customer policy empowering agents to disengage, plus wellbeing support.",
    { flags: ["mental_health"], status: "actioned", response: "A new policy lets agents end abusive calls after one warning, and team leads will debrief after escalations." }),
  f(ENG, 6, ["positive", 0.4, "low"], ["Tools & Resources"], ["pleased"],
    "Thanks for approving the new laptops. Build times halved.",
    "New laptops halved build times.",
    "Plan regular hardware refresh cycles.", { category: "Appreciation", status: "closed" }),
  f(HR, 4, ["mixed", -0.1, "low"], ["Communication"], ["concerned"],
    "Employees tell us all-hands feel like broadcasts. There is no real Q&A time and hard questions are skipped.",
    "All-hands lack genuine Q&A and avoid hard questions.",
    "Reserve 20 minutes of all-hands for anonymous, upvoted Q&A.", { category: "Suggestion", status: "in_review" }),
  f(SAL, 1, ["negative", -0.6, "high"], ["Management & Leadership", "Team Culture"], ["intimidated"],
    "Our regional director shouts at reps on the pipeline call when numbers are down. People are scared to report bad news.",
    "Sales director reportedly shouts at reps, creating fear of reporting bad news.",
    "Speak with the director's leader, gather more context confidentially, and set behavioural expectations.",
    { channel: "voice", flags: ["harassment"], status: "new" }),
  f(PRD, 3, ["positive", 0.5, "low"], ["Recognition", "Team Culture"], ["appreciated"],
    "Peer-recognition kudos channel is small but lovely. Nice to see cross-team thank-yous.",
    "Peer kudos channel builds cross-team appreciation.",
    "Promote the kudos channel and feature highlights in newsletters.", { category: "Appreciation", status: "closed" }),
  f(ENG, 4, ["mixed", -0.2, "medium"], ["Career Growth", "Management & Leadership"], ["uncertain"],
    "Performance reviews are next month and my manager has cancelled our last four 1:1s because of the launch.",
    "Manager cancelled four 1:1s before performance reviews.",
    "Remind managers that 1:1s are protected time, especially before reviews.", { status: "in_review" }),
  f(OPS, 2, ["positive", 0.6, "low"], ["Recognition", "Management & Leadership"], ["valued"],
    "Our new shift supervisor thanks us at the end of every shift and fixed the roster problem in a week. Morale is much better.",
    "New shift supervisor improved morale through recognition and fixing rosters.",
    "Recognise the supervisor and share their practices.", { channel: "ocr", category: "Appreciation", status: "new" }),
  f(SUP, 5, ["mixed", 0.0, "low"], ["Remote & Hybrid Work"], ["neutral"],
    "Support needs quiet space in the office to take calls. The open floor is too noisy for customer calls.",
    "Support needs quiet call space on office days.",
    "Allocate quiet call zones for support on office days.", { category: "Suggestion", status: "in_review" }),
  f(FIN, 2, ["positive", 0.4, "low"], ["Team Culture"], ["content"],
    "Team is small but supportive. My manager is flexible when I need time for family.",
    "Supportive finance team and flexible manager.",
    "No action needed; recognise the manager.", { category: "Appreciation", status: "new",
      identified: { name: "Kavya Rao", email: "kavya.rao@acme.example" } }),
  f(SAL, 4, ["mixed", -0.1, "medium"], ["Compensation & Benefits"], ["uncertain"],
    "I did not understand the new commission plan. Please also explain it in Hindi with an example.",
    "Employee did not understand the new commission plan and requests an explanation with examples in Hindi.",
    "Provide commission plan explainer with examples in Hindi.",
    {
      language: "Hindi",
      channel: "voice",
      raw: "मुझे नया कमीशन प्लान समझ नहीं आया। कृपया हिंदी में भी एक उदाहरण के साथ समझाइए।",
      category: "Concern",
      status: "actioned",
      response: "A Hindi version of the commission explainer with worked examples is now on the intranet.",
      identified: { name: "Rohit Verma", email: "rohit.verma@acme.example" },
    }),
  f(ENG, 3, ["mixed", 0.0, "medium"], ["Diversity & Inclusion", "Team Culture"], ["isolated"],
    "Team socials are always drinks after work. As someone who does not drink and has a long commute, I always miss out.",
    "After-work drinks as the only social format excludes some employees.",
    "Encourage varied, inclusive social formats during work hours.", { category: "Suggestion", status: "new" }),
  f(MKT, 6, ["negative", -0.4, "medium"], ["Career Growth", "Compensation & Benefits"], ["overlooked"],
    "I have taken on the work of the person who left but my title and pay stayed the same for six months.",
    "Employee absorbed a departed colleague's work without title or pay change.",
    "Review role scope and compensation for the employee's expanded responsibilities.", { flags: ["attrition_risk"], status: "in_review" }),
  f(SUP, 10, ["neutral", 0.0, "low"], ["Communication"], ["neutral"],
    "It would help if product release notes reached support before customers start asking about new features.",
    "Support needs release notes before customers learn of changes.",
    "Add support to the release-notes distribution before launches.", { category: "Suggestion", status: "closed" }),
  f(PRD, 7, ["mixed", 0.0, "low"], ["Tools & Resources"], ["neutral"],
    "Too many tools: Jira, Linear, Notion and Confluence. Nobody knows where the source of truth is.",
    "Tool sprawl leaves no clear source of truth.",
    "Rationalise planning and documentation tools.", { category: "Suggestion", status: "closed" }),
  f(DES, 2, ["negative", -0.4, "medium"], ["Workload & Burnout"], ["stretched"],
    "Two designers supporting six product squads during the launch. We are always the bottleneck and it is not our fault.",
    "Two designers stretched across six squads during launch.",
    "Review design staffing ratios against the roadmap.", { status: "new" }),
  f(ENG, 7, ["neutral", 0.0, "low"], ["Communication"], ["neutral"],
    "Would love more visibility into why some projects get cancelled. Engineers find out last.",
    "Engineers want clearer communication on project cancellations.",
    "Share project decision rationale in engineering updates.", { category: "Suggestion", status: "closed" }),
  f(OPS, 4, ["negative", -0.5, "high"], ["Management & Leadership", "Diversity & Inclusion"], ["unfair"],
    "Overtime shifts always go to the supervisor's friends. The rest of us are never offered the extra pay.",
    "Overtime allocation perceived as favouritism.",
    "Introduce a transparent overtime rota and review recent allocations.", { channel: "ocr", status: "in_review" }),
  f(MKT, 10, ["positive", 0.5, "low"], ["Work-Life Balance"], ["grateful"],
    "Thank you for the extra wellness day after the big launch. Really needed it.",
    "Wellness day after launch was appreciated.",
    "Institutionalise recovery days after major launches.", { category: "Appreciation", status: "closed" }),

  // ── More multilingual & recent voices ─────────────────────────────────────
  f(ENG, 1, ["negative", -0.7, "high"], ["Workload & Burnout", "Work-Life Balance"], ["exhausted"],
    "I missed my sister's wedding functions because of the launch. My family is upset and honestly so am I.",
    "Engineer missed family wedding events due to launch workload.",
    "Ensure leave is protected and back-fill critical launch roles.",
    {
      language: "Kannada",
      channel: "voice",
      raw: "ಲಾಂಚ್ ಕಾರಣದಿಂದ ನನ್ನ ತಂಗಿಯ ಮದುವೆಯ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ತಪ್ಪಿಸಿಕೊಂಡೆ. ನನ್ನ ಕುಟುಂಬ ಬೇಸರಗೊಂಡಿದೆ, ನಾನೂ ಕೂಡ.",
      flags: ["burnout"],
      status: "new",
    }),
  f(SUP, 4, ["positive", 0.7, "low"], ["Tools & Resources", "Work-Life Balance"], ["happy"],
    "With the new helpdesk I finish my tickets on time and can go home to my kids. Thank you very much.",
    "New helpdesk lets agent finish on time and spend evenings with family.",
    "Share the tooling impact story in the internal newsletter.",
    {
      language: "Spanish",
      raw: "Con el nuevo helpdesk termino mis tickets a tiempo y puedo ir a casa con mis hijos. Muchas gracias.",
      category: "Appreciation",
      status: "closed",
    }),
  f(OPS, 6, ["negative", -0.5, "medium"], ["Workplace Safety", "Tools & Resources"], ["worried"],
    "Safety shoes and gloves have not been replaced in months. Many of us are working with torn gloves.",
    "Worn-out safety shoes and gloves not replaced for months.",
    "Replace PPE immediately and set a replacement schedule.",
    {
      language: "Tamil",
      channel: "ocr",
      raw: "பாதுகாப்பு காலணிகள் மற்றும் கையுறைகள் பல மாதங்களாக மாற்றப்படவில்லை. பலர் கிழிந்த கையுறைகளுடன் வேலை செய்கிறோம்.",
      flags: ["safety"],
      status: "actioned",
      response: "New PPE kits were distributed this week and will be replaced every quarter.",
    }),
  f(FIN, 4, ["mixed", -0.1, "low"], ["Remote & Hybrid Work", "Work-Life Balance"], ["tired"],
    "Travelling to the office three days a week takes two hours every day. Please allow flexibility for people with long commutes.",
    "Long commute makes three office days hard; asks for flexibility.",
    "Offer commute-based exceptions in the hybrid policy.",
    {
      language: "Hindi",
      raw: "हफ्ते में तीन दिन ऑफिस आने में रोज़ दो घंटे लगते हैं। लंबी दूरी वालों के लिए थोड़ी छूट दीजिए।",
      category: "Suggestion",
      status: "in_review",
    }),
  f(SAL, 0, ["mixed", 0.0, "medium"], ["Compensation & Benefits", "Career Growth"], ["uncertain"],
    "I closed my biggest deal this quarter but under the new plan I earn less than last year. I don't know if staying here makes sense.",
    "Top-performing rep earns less under the new plan and questions staying.",
    "Review outlier earnings impacts of the new plan and hold a retention conversation.",
    { flags: ["attrition_risk"], status: "new" }),
  f(ENG, 0, ["negative", -0.6, "high"], ["Workload & Burnout", "Communication"], ["frustrated"],
    "We raised the burnout issue in the last pulse survey and in retro. Nothing changed. People are losing faith that feedback matters.",
    "Repeatedly raised burnout concerns saw no visible action, eroding trust.",
    "Publicly acknowledge the engineering burnout signal and commit to specific actions with dates.",
    { flags: ["burnout", "attrition_risk"], status: "new" }),
  f(ENG, 2, ["negative", -0.5, "medium"], ["Workload & Burnout", "Management & Leadership"], ["stressed"],
    "Incident postmortems keep producing action items that never get prioritised, so the same incidents recur and page us again.",
    "Postmortem action items are never prioritised, causing repeat incidents.",
    "Reserve sprint capacity for postmortem follow-ups.", { status: "new" }),
  f(PRD, 1, ["positive", 0.4, "low"], ["Team Culture", "Recognition"], ["grateful"],
    "The engineering team has been heroic during this launch. They deserve more than a thank-you message.",
    "PM calls for tangible recognition of engineering's launch effort.",
    "Plan tangible recognition (spot bonus, recovery days) for the launch team.", { category: "Appreciation", status: "new" }),
  f(DES, 0, ["mixed", 0.0, "low"], ["Remote & Hybrid Work", "Team Culture"], ["content"],
    "Now that teams choose anchor days, office days feel purposeful. Much better than the original rule.",
    "Team-chosen anchor days made office time more purposeful.",
    "Share the anchor-day outcome as a 'you said, we did' update.", { category: "Appreciation", status: "new" }),
  f(SUP, 0, ["positive", 0.6, "low"], ["Onboarding & Training", "Tools & Resources"], ["confident"],
    "New hires in support ramp up in two weeks now instead of six thanks to the helpdesk knowledge base.",
    "Support new-hire ramp time dropped from six to two weeks.",
    "Document the knowledge-base approach for other teams.", { category: "Appreciation", status: "new" }),
  f(HR, 1, ["mixed", -0.1, "medium"], ["Workload & Burnout", "Management & Leadership"], ["concerned"],
    "Sick leave requests in engineering doubled this month compared with last quarter. That matches what we hear informally.",
    "Engineering sick leave requests doubled month over month.",
    "Correlate leave data with feedback and brief engineering leadership.", { status: "new" }),
  f(MKT, 2, ["positive", 0.5, "low"], ["Career Growth", "Onboarding & Training"], ["motivated"],
    "The learning stipend finally got approved. I've enrolled in a data analytics course. Thank you!",
    "Employee appreciates learning stipend approval.",
    "Promote learning stipend usage across teams.", { category: "Appreciation", status: "new" }),
];
